### ISSUE TITLE
The reproduced results cannot meet the expectations of the paper

### ISSUE THREAD

**Issue by jiangchaokang** [davezdeng8/rsf#1]
Hello, I ran your open-source code, but the results I obtained are as follows: 
stereokitti8192:
epe : 0.052147935109031436
median_epe : 0.03162627722739397
acc3d_s : 0.8741146465991214
acc3d_r : 0.922730776314023
outlier : 0.1887290830442527
n : 8185.330311603031
precision_f : 0.9274372638029652
precision_b : 0.9550857502835088
recall_f : 0.9155866645099155
recall_b : 0.9522098968822503
accuracy : 0.9499134432014603
contains_moving : 1.0
tp : 3102.5763399894
fp : 183.28511987114626
fn : 225.3978806588611
tn : 4674.0709710836245
IOU : 0.8832681625859753
mIOU : 0.9013075788427645
------------------------------
stereokitti　All:
epe : 0.03610315639361909
median_epe : 0.018780625211296732
acc3d_s : 0.900131079681551
acc3d_r : 0.9633488190514978
outlier : 0.14820010337833053
n : 37911.98101389553
precision_f : 0.9093838240202443
precision_b : 0.9754847834799701
recall_f : 0.9485112758159975
recall_b : 0.9262627632126569
accuracy : 0.9553014024213471
contains_moving : 1.0
tp : 15766.888473814506
fp : 975.7575139216593
fn : 368.65774904624294
tn : 20800.67727711312
IOU : 0.8978355481084549
mIOU : 0.9121095727857198

Why can't I achieve the results in Table 1 of the paper? I'm looking forward to your reply, thank you very much!

**Comment by jiangchaokang** [comment]
I found that the number of epochs can affect the final results. Besides that, what other parameters can be modified to improve the final results? Looking forward to your reply..

**Comment by ShaneCan** [comment]
can you visualize the final results? which .py you used? plz help... really appreciate that!
